from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Sequence, Tuple

from .svg_import import polyline_bounds

Point = Tuple[float, float]
Polyline = List[Point]


@dataclass
class MachineConfig:
    name: str = "default-plotter"
    units: str = "mm"
    origin_x_mm: float = 0.0
    origin_y_mm: float = 0.0
    scale: float = 1.0
    invert_x: bool = False
    invert_y: bool = False
    feed_mm_min: float = 1200.0
    travel_mm_min: float = 3000.0
    servo_dwell_ms: int = 120
    pen_up_command: str = "M5"
    pen_down_command: str = "M3"
    pen_up_angle: int = 30
    pen_down_angle: int = 70
    font_path: str = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    font_size_mm: float = 12.0
    line_height_mm: float | None = None
    letter_spacing_mm: float = 0.0
    flatten_tolerance_mm: float = 0.35

    @classmethod
    def from_dict(cls, data: dict | None) -> "MachineConfig":
        if not data:
            return cls()
        valid = {field.name for field in cls.__dataclass_fields__.values()}
        kwargs = {k: v for k, v in data.items() if k in valid}
        return cls(**kwargs)

    @classmethod
    def from_json(cls, path: str | Path) -> "MachineConfig":
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls.from_dict(data)

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)


def _fmt(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text if text else "0"


def _transform_polylines(polylines: Sequence[Polyline], cfg: MachineConfig) -> List[Polyline]:
    bounds = polyline_bounds(polylines)
    if bounds is None:
        return []

    min_x, min_y, max_x, max_y = bounds
    width = max_x - min_x
    height = max_y - min_y
    scale = float(cfg.scale)

    transformed: List[Polyline] = []
    for poly in polylines:
        new_poly: Polyline = []
        for x, y in poly:
            nx = (x - min_x) * scale
            ny = (y - min_y) * scale
            if cfg.invert_x:
                nx = width * scale - nx
            if cfg.invert_y:
                ny = height * scale - ny
            new_poly.append((cfg.origin_x_mm + nx, cfg.origin_y_mm + ny))
        transformed.append(new_poly)
    return transformed


def generate_gcode(
    polylines: Sequence[Polyline],
    cfg: MachineConfig | None = None,
    source_name: str = "input",
) -> str:
    cfg = cfg or MachineConfig()
    transformed = _transform_polylines(polylines, cfg)
    bounds = polyline_bounds(transformed)

    lines: list[str] = []
    lines.append("; generated by text-svg-to-gcode")
    lines.append(f"; source: {source_name}")
    lines.append(f"; machine: {cfg.name}")
    lines.append(f"; units: {cfg.units}")
    lines.append(f"; pen_up_command: {cfg.pen_up_command}")
    lines.append(f"; pen_down_command: {cfg.pen_down_command}")
    lines.append(f"; pen_up_angle: {cfg.pen_up_angle}")
    lines.append(f"; pen_down_angle: {cfg.pen_down_angle}")
    if bounds is not None:
        min_x, min_y, max_x, max_y = bounds
        lines.append(f"; bounds_mm: min=({_fmt(min_x)}, {_fmt(min_y)}) max=({_fmt(max_x)}, {_fmt(max_y)})")
    lines.append("G21")
    lines.append("G90")
    if cfg.pen_up_command:
        lines.append(cfg.pen_up_command)
    lines.append("")

    for index, poly in enumerate(transformed, start=1):
        if len(poly) < 2:
            continue
        start_x, start_y = poly[0]
        lines.append(f"; segment {index}")
        lines.append(f"G0 X{_fmt(start_x)} Y{_fmt(start_y)}")
        if cfg.pen_down_command:
            lines.append(cfg.pen_down_command)
        if cfg.servo_dwell_ms:
            lines.append(f"G4 P{int(cfg.servo_dwell_ms)}")
        for x, y in poly[1:]:
            lines.append(f"G1 X{_fmt(x)} Y{_fmt(y)} F{_fmt(cfg.feed_mm_min)}")
        if cfg.pen_up_command:
            lines.append(cfg.pen_up_command)
        if cfg.servo_dwell_ms:
            lines.append(f"G4 P{int(cfg.servo_dwell_ms)}")
        lines.append("")

    lines.append("M2")
    return "\n".join(lines).rstrip() + "\n"
